import '@/styles/globals.css'
import { store } from "../redux/store"
import { Provider } from "react-redux"

import { ChakraProvider } from '@chakra-ui/react'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return (
    <Provider store={store} >
      <ChakraProvider>
        <Head>
          <title>Poke-redux</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </ChakraProvider>
    </Provider>
  )
}
