import '@/styles/globals.css'
import { store } from "../redux/store"
import { Provider } from "react-redux"

import { Box, ChakraProvider } from '@chakra-ui/react'
import Head from 'next/head'
import Footer from '@/components/Footer'

export default function App({ Component, pageProps }) {
  return (
    <Provider store={store} >
      <ChakraProvider>
        <Head>
          <title>Poke-redux</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <script src="https://kit.fontawesome.com/248d93b7fa.js" crossorigin="anonymous"></script>
        </Head>
        <Box bg={"#FFE4B5"} minHeight="100vh" p={8} w="100%">
          <Component {...pageProps} />
        </Box>
        <Footer />
      </ChakraProvider>
    </Provider>
  )
}
